import { computed } from 'vue'

export type AssistantResponseType = 'text' | 'gallery' | 'devicemap' | 'calendar' | 'memory' | 'history'
export type AssistantSourceId = 'screen' | 'phone' | 'office'
export type AssistantTone = '' | 'ok' | 'warn' | 'violet'
export type AssistantDeviceStatus = 'on' | 'warn' | 'off'

export interface AssistantResponse {
  type: AssistantResponseType
  query: string
  focus?: string
}

export interface AssistantSource {
  id: AssistantSourceId
  label: string
  icon: string
}

export interface AssistantSuggestion {
  icon: string
  label: string
}

export interface AssistantDevice {
  id: string
  name: string
  meta: string
  icon: string
  x: number
  y: number
  hub?: boolean
  status: AssistantDeviceStatus
}

export interface AssistantCalendarEvent {
  h: number
  label: string
  meta: string
  tone: AssistantTone
}

export interface AssistantMemoryItem {
  icon: string
  title: string
  body: string
  meta: string
}

export interface AssistantMemoryGroup {
  group: string
  items: AssistantMemoryItem[]
}

export interface AssistantHistoryItem {
  time: string
  q: string
  type: string
  tags: string[]
  acc?: boolean
}

export interface AssistantHistoryGroup {
  group: string
  count: number
  items: AssistantHistoryItem[]
}

export interface AssistantEvent {
  id: string
  source: string
  icon: string
  toast: {
    lead: string
    sub: string
  }
  respond: 'door-motion' | 'deploy' | 'calendar'
}

export interface AssistantGalleryItem {
  tag: string
  cap: string
  sub: string
  gradient: string
}

export interface AssistantTextPoint {
  title: string
  body: string
}

export interface AssistantTextSource {
  title: string
  url: string
  color: string
  initials: string
}

export interface AssistantTextAnswer {
  lead: string
  points: AssistantTextPoint[]
  sources: AssistantTextSource[]
}

export interface AssistantSnapshot {
  sources: AssistantSource[]
  suggestions: AssistantSuggestion[]
  devices: AssistantDevice[]
  calendarEvents: AssistantCalendarEvent[]
  memory: AssistantMemoryGroup[]
  history: AssistantHistoryGroup[]
  events: AssistantEvent[]
  gallery: AssistantGalleryItem[]
}

export interface AssistantMessageOptions {
  model?: string
}

const truthyFlags = new Set(['1', 'true', 'yes', 'on'])

const ASSISTANT_ENDPOINTS = {
  snapshot: '/assistant/snapshot',
  messages: '/assistant/messages',
  events: '/assistant/events'
} as const

const sources: AssistantSource[] = [
  { id: 'screen', label: 'This screen', icon: 'monitor' },
  { id: 'phone', label: 'Phone', icon: 'smartphone' },
  { id: 'office', label: 'Office mic', icon: 'mic' }
]

const suggestions: AssistantSuggestion[] = [
  { icon: 'radio', label: 'Show me the home network' },
  { icon: 'calendar-days', label: "What's on today?" },
  { icon: 'images', label: 'Photos from the Porto trip' },
  { icon: 'sparkles', label: "How's the deploy looking?" }
]

const devices: AssistantDevice[] = [
  { id: 'router', name: 'Core Router', meta: 'Gateway - 1.2 Gb/s', icon: 'router', x: 50, y: 50, hub: true, status: 'on' },
  { id: 'living-tv', name: 'Living Room TV', meta: 'Wi-Fi 6, -48 dBm', icon: 'tv', x: 22, y: 24, status: 'on' },
  { id: 'thermo', name: 'Thermostat', meta: 'Zigbee - 21.4 C', icon: 'thermometer', x: 80, y: 22, status: 'on' },
  { id: 'door', name: 'Front Door Cam', meta: 'PoE - streaming', icon: 'video', x: 84, y: 60, status: 'warn' },
  { id: 'speaker', name: 'Kitchen Speaker', meta: 'Wi-Fi - idle', icon: 'speaker', x: 18, y: 70, status: 'on' },
  { id: 'phone', name: 'Pixel - Alex', meta: 'Wi-Fi 6E, -52 dBm', icon: 'smartphone', x: 50, y: 86, status: 'on' },
  { id: 'lights', name: 'Studio Lights', meta: 'Zigbee - 4 nodes', icon: 'lightbulb', x: 73, y: 84, status: 'on' },
  { id: 'nas', name: 'Vault NAS', meta: '10 GbE - 4.1 TB free', icon: 'hard-drive', x: 30, y: 50, status: 'on' }
]

const calendarEvents: AssistantCalendarEvent[] = [
  { h: 8, label: 'Morning brief', meta: '08:00 - Auto-generated by Jarvis', tone: 'violet' },
  { h: 9, label: 'Standup - Platform', meta: '09:30 - Meet - 6 people', tone: '' },
  { h: 11, label: 'Design review: Console v2', meta: '11:00 to 12:00 - Studio', tone: '' },
  { h: 13, label: 'Lunch with Priya', meta: '13:00 - Toki, downtown', tone: 'ok' },
  { h: 15, label: 'Deploy window', meta: '15:00 to 15:45 - prod-eu', tone: 'warn' },
  { h: 17, label: 'Pick up dry cleaning', meta: '17:30 - reminder', tone: '' },
  { h: 19, label: 'Dinner - Ravi and Mei', meta: '19:30 - home', tone: 'violet' }
]

const memory: AssistantMemoryGroup[] = [
  {
    group: 'About you',
    items: [
      { icon: 'user', title: 'Alex', body: 'Prefers concise answers, metric units, and 24-hour time.', meta: 'Stable preference' },
      { icon: 'briefcase', title: 'Platform owner', body: 'Staff engineer on the Platform team; owns the deploy pipeline.', meta: 'Updated 3 weeks ago' },
      { icon: 'map-pin', title: 'Home base', body: 'Based in Lisbon. Home office is the north-facing studio.', meta: 'Stable' }
    ]
  },
  {
    group: 'Preferences',
    items: [
      { icon: 'moon', title: 'Theme', body: 'Switch to dark theme automatically after sunset.', meta: 'Rule - active' },
      { icon: 'bell-off', title: 'Focus blocks', body: 'No proactive interruptions from 09:00 to 11:00.', meta: 'Rule - active' },
      { icon: 'volume-2', title: 'Voice replies', body: 'Off on the wall display; enabled on phone.', meta: 'Per-device' }
    ]
  },
  {
    group: 'Context Jarvis is tracking',
    items: [
      { icon: 'git-branch', title: 'prod-eu deploy', body: 'Watching the 15:00 deploy and surfacing health anomalies.', meta: 'Expires today 16:00' },
      { icon: 'package', title: 'Parcel', body: 'Out for delivery with ETA 14:20.', meta: 'Live' },
      { icon: 'plane', title: 'Porto trip', body: 'Flights and hotel saved for next Friday.', meta: 'Reference' }
    ]
  }
]

const history: AssistantHistoryGroup[] = [
  {
    group: 'Earlier today',
    count: 5,
    items: [
      { time: '13:48', q: 'Show me the home network', type: 'Network map', tags: ['Devices', 'Screen'], acc: true },
      { time: '11:12', q: 'Photos from the Porto scouting trip', type: 'Gallery', tags: ['Images', 'Phone'] },
      { time: '09:31', q: "What's on my calendar today?", type: 'Schedule', tags: ['Calendar', 'Voice'] },
      { time: '08:00', q: 'Morning brief', type: 'Briefing', tags: ['Scheduled', 'Auto'], acc: true },
      { time: '07:42', q: 'Is the deploy window still at 15:00?', type: 'Answer', tags: ['Voice', 'Phone'] }
    ]
  },
  {
    group: 'Yesterday',
    count: 3,
    items: [
      { time: '21:10', q: 'Dim the studio lights to 30%', type: 'Action', tags: ['Devices', 'Voice'] },
      { time: '16:25', q: 'Summarize the Console v2 review notes', type: 'Answer', tags: ['Docs'] },
      { time: '14:03', q: 'Front door - who was that?', type: 'Network map', tags: ['Camera', 'Event'], acc: true }
    ]
  },
  {
    group: 'This week - Porto trip',
    count: 4,
    items: [
      { time: 'Mon', q: 'Find hotels near Ribeira under EUR 180', type: 'Answer', tags: ['Research'] },
      { time: 'Mon', q: 'Show me the riverfront at sunset', type: 'Gallery', tags: ['Images'] },
      { time: 'Sun', q: 'Flights Lisbon to Porto Friday morning', type: 'Answer', tags: ['Research', 'Phone'] },
      { time: 'Sun', q: 'Block Friday afternoon for travel', type: 'Schedule', tags: ['Calendar'] }
    ]
  }
]

const events: AssistantEvent[] = [
  {
    id: 'door',
    source: 'Front Door Cam',
    icon: 'video',
    toast: {
      lead: 'Motion at the front door',
      sub: 'A delivery courier. The parcel matches your tracked delivery.'
    },
    respond: 'door-motion'
  },
  {
    id: 'deploy',
    source: 'Deploy watcher',
    icon: 'git-branch',
    toast: {
      lead: 'prod-eu deploy starting',
      sub: "Health looks nominal. I'll watch error rates."
    },
    respond: 'deploy'
  },
  {
    id: 'brief',
    source: 'Schedule',
    icon: 'sunrise',
    toast: {
      lead: 'Your morning brief is ready',
      sub: '3 meetings, clear skies, 1 deploy window.'
    },
    respond: 'calendar'
  }
]

const gallery: AssistantGalleryItem[] = [
  {
    tag: 'Featured',
    cap: 'Ribeira at golden hour',
    sub: 'Porto - 19:42',
    gradient: 'linear-gradient(135deg,#2A53E6,#9B5CFF 60%,#B27DFF)'
  },
  {
    tag: '',
    cap: 'Dom Luis bridge',
    sub: 'Porto',
    gradient: 'linear-gradient(160deg,#1b2030,#3B6CFF 120%)'
  },
  {
    tag: '',
    cap: 'Riverfront cafes',
    sub: 'Cais da Ribeira',
    gradient: 'linear-gradient(135deg,#6E8CFF,#ECEAE5 130%)'
  },
  {
    tag: '',
    cap: 'Azulejo facade',
    sub: 'Sao Bento',
    gradient: 'linear-gradient(150deg,#7E3FE6,#3B6CFF)'
  },
  {
    tag: '',
    cap: 'Old town alley',
    sub: 'Porto',
    gradient: 'linear-gradient(120deg,#B27DFF,#6E8CFF 80%)'
  }
]

export const assistantTextAnswers: Record<'default' | 'deploy', AssistantTextAnswer> = {
  deploy: {
    lead: 'The prod-eu deploy is queued for 15:00 and currently looks healthy. No blocker is visible in the local snapshot.',
    points: [
      { title: 'Pipeline green', body: 'All 214 checks passed on main; image build metadata is fresh.' },
      { title: 'Error budget intact', body: 'Availability is inside the target window for this week.' },
      { title: 'Watch item', body: 'The EU cache node restarted overnight. Jarvis will flag latency above 200 ms.' }
    ],
    sources: [
      { title: 'CI run #4821', url: 'pipeline.internal', color: '#3B6CFF', initials: 'CI' },
      { title: 'SLO dashboard', url: 'grafana.internal', color: '#9B5CFF', initials: 'GR' }
    ]
  },
  default: {
    lead: "Here's the short version. Jarvis has the local context loaded and can render the useful view instead of only describing it.",
    points: [
      { title: 'Continuous context', body: 'Conversation, tools, and remembered preferences stay in one running workspace.' },
      { title: 'Visual answers', body: 'Requests can become maps, galleries, schedule views, or concise text summaries.' },
      { title: 'Local-first record', body: 'Memory and history are modeled as local data that backend services can own later.' }
    ],
    sources: [
      { title: 'Jarvis memory', url: 'on-device', color: '#3B6CFF', initials: 'J' }
    ]
  }
}

export const assistantSnapshot: AssistantSnapshot = {
  sources,
  suggestions,
  devices,
  calendarEvents,
  memory,
  history,
  events,
  gallery
}

const cloneSnapshot = (snapshot: AssistantSnapshot): AssistantSnapshot =>
  JSON.parse(JSON.stringify(snapshot)) as AssistantSnapshot

const isTruthy = (value: unknown) =>
  typeof value === 'string'
    ? truthyFlags.has(value.toLowerCase())
    : Boolean(value)

export const routeAssistantIntent = (raw: string): AssistantResponse => {
  const query = (raw || '').trim()
  const q = query.toLowerCase()
  const has = (...words: string[]) => words.some((word) => q.includes(word))

  if (has('network', 'devices', 'wifi', 'wi-fi', 'router', 'door', 'camera', 'map', 'connected', 'online')) {
    return { type: 'devicemap', query }
  }

  if (has('photo', 'image', 'picture', 'gallery', 'show me', 'porto', 'trip', 'riverfront', 'sunset', 'scout')) {
    return { type: 'gallery', query }
  }

  if (has('calendar', 'schedule', 'today', 'tomorrow', 'meeting', 'agenda', 'brief', 'standup', 'free', 'busy')) {
    return { type: 'calendar', query }
  }

  return { type: 'text', query }
}

export const pickAssistantTextAnswer = (query: string) => {
  const q = query.toLowerCase()
  if (q.includes('deploy') || q.includes('prod') || q.includes('pipeline')) {
    return assistantTextAnswers.deploy
  }
  return assistantTextAnswers.default
}

const normalizeResponse = (payload: any, fallbackQuery: string): AssistantResponse => {
  const fallback = routeAssistantIntent(fallbackQuery)
  const allowed: AssistantResponseType[] = ['text', 'gallery', 'devicemap', 'calendar', 'memory', 'history']
  const type = allowed.includes(payload?.type) ? payload.type : fallback.type
  return {
    type,
    query: typeof payload?.query === 'string' ? payload.query : fallbackQuery,
    focus: typeof payload?.focus === 'string' ? payload.focus : undefined
  }
}

const normalizeSnapshot = (payload: any): AssistantSnapshot => ({
  sources: Array.isArray(payload?.sources) ? payload.sources : sources,
  suggestions: Array.isArray(payload?.suggestions) ? payload.suggestions : suggestions,
  devices: Array.isArray(payload?.devices) ? payload.devices : devices,
  calendarEvents: Array.isArray(payload?.calendarEvents) ? payload.calendarEvents : calendarEvents,
  memory: Array.isArray(payload?.memory) ? payload.memory : memory,
  history: Array.isArray(payload?.history) ? payload.history : history,
  events: Array.isArray(payload?.events) ? payload.events : events,
  gallery: Array.isArray(payload?.gallery) ? payload.gallery : gallery
})

export const useAssistantConsoleApi = () => {
  const runtimeConfig = useRuntimeConfig()
  const backendEnabled = computed(() => isTruthy(runtimeConfig.public?.assistantApiEnabled))

  const loadSnapshot = async (): Promise<AssistantSnapshot> => {
    if (!backendEnabled.value) return cloneSnapshot(assistantSnapshot)

    const { data, error } = await useApiFetch('GET', ASSISTANT_ENDPOINTS.snapshot)
    if (error || !data) return cloneSnapshot(assistantSnapshot)
    return normalizeSnapshot(data)
  }

  const sendMessage = async (
    message: string,
    source: AssistantSourceId = 'screen',
    options: AssistantMessageOptions = {}
  ): Promise<AssistantResponse> => {
    if (!backendEnabled.value) return routeAssistantIntent(message)

    const { data, error } = await useApiFetch('POST', ASSISTANT_ENDPOINTS.messages, {
      message,
      source,
      model: options.model
    })

    if (error || !data) return routeAssistantIntent(message)
    return normalizeResponse(data, message)
  }

  const triggerEvent = async (eventId: string): Promise<AssistantEvent | null> => {
    const localEvent = events.find((event) => event.id === eventId) ?? null
    if (!backendEnabled.value) return localEvent

    const { data, error } = await useApiFetch('POST', ASSISTANT_ENDPOINTS.events, { eventId })
    if (error || !data) return localEvent
    return (data as AssistantEvent) ?? localEvent
  }

  return {
    backendEnabled,
    endpoints: ASSISTANT_ENDPOINTS,
    loadSnapshot,
    sendMessage,
    triggerEvent
  }
}
