/* JARVIS — mock data + intent router */

/* ---- gradient palettes for image-gallery placeholders (cool-toned, high-key) ---- */
const GAL_GRADIENTS = [
  'linear-gradient(135deg,#2A53E6,#9B5CFF 60%,#B27DFF)',
  'linear-gradient(160deg,#1b2030,#3B6CFF 120%)',
  'linear-gradient(135deg,#6E8CFF,#ECEAE5 130%)',
  'linear-gradient(150deg,#7E3FE6,#3B6CFF)',
  'linear-gradient(135deg,#0E1015,#2A53E6 140%)',
  'linear-gradient(120deg,#B27DFF,#6E8CFF 80%)',
];

/* ---- DEVICES for the network map ---- */
const DEVICES = [
  { id: 'router', name: 'Core Router', meta: 'Gateway · 1.2 Gb/s', icon: 'router', x: 50, y: 50, hub: true, status: 'on' },
  { id: 'living-tv', name: 'Living Room TV', meta: 'Wi-Fi 6 · −48 dBm', icon: 'tv', x: 22, y: 24, status: 'on' },
  { id: 'thermo', name: 'Thermostat', meta: 'Zigbee · 21.4°C', icon: 'thermometer', x: 80, y: 22, status: 'on' },
  { id: 'door', name: 'Front Door Cam', meta: 'PoE · streaming', icon: 'video', x: 84, y: 60, status: 'warn' },
  { id: 'speaker', name: 'Kitchen Speaker', meta: 'Wi-Fi · idle', icon: 'speaker', x: 18, y: 70, status: 'on' },
  { id: 'phone', name: 'Pixel — Alex', meta: 'Wi-Fi 6E · −52 dBm', icon: 'smartphone', x: 50, y: 86, status: 'on' },
  { id: 'lights', name: 'Studio Lights', meta: 'Zigbee · 4 nodes', icon: 'lightbulb', x: 73, y: 84, status: 'on' },
  { id: 'nas', name: 'Vault NAS', meta: '10 GbE · 4.1 TB free', icon: 'hard-drive', x: 30, y: 50, status: 'on' },
];

/* ---- CALENDAR events for today ---- */
const CAL_EVENTS = [
  { h: 8, label: 'Morning brief', meta: '08:00 · Auto-generated by Jarvis', tone: 'violet' },
  { h: 9, label: 'Standup — Platform', meta: '09:30 · Meet · 6 people', tone: '' },
  { h: 11, label: 'Design review: Console v2', meta: '11:00 → 12:00 · Studio', tone: '' },
  { h: 13, label: 'Lunch w/ Priya', meta: '13:00 · Toki, downtown', tone: 'ok' },
  { h: 15, label: 'Deploy window', meta: '15:00 → 15:45 · prod-eu', tone: 'warn' },
  { h: 17, label: 'Pick up dry cleaning', meta: '17:30 · reminder', tone: '' },
  { h: 19, label: 'Dinner — Ravi & Mei', meta: '19:30 · home', tone: 'violet' },
];

/* ---- MEMORY: what Jarvis knows ---- */
const MEMORY = [
  { group: 'About you', items: [
    { icon: 'user', t: 'Goes by <b>Alex</b>. Prefers concise answers, metric units, 24-hour time.', meta: 'Stable preference' },
    { icon: 'briefcase', t: 'Staff engineer on the <b>Platform</b> team. Owns the deploy pipeline.', meta: 'Updated 3 weeks ago' },
    { icon: 'map-pin', t: 'Based in <b>Lisbon</b>. Home office is the studio (north-facing).', meta: 'Stable' },
  ]},
  { group: 'Preferences', items: [
    { icon: 'moon', t: 'Switch to <b>dark theme</b> automatically after sunset.', meta: 'Rule · active' },
    { icon: 'bell-off', t: 'No proactive interruptions during <b>focus blocks</b> (09:00–11:00).', meta: 'Rule · active' },
    { icon: 'volume-2', t: 'Voice replies <b>off</b> on the wall display; on for phone.', meta: 'Per-device' },
  ]},
  { group: 'Context Jarvis is tracking', items: [
    { icon: 'git-branch', t: 'Watching <b>prod-eu deploy</b> at 15:00 — will surface health if anomalies appear.', meta: 'Expires today 16:00' },
    { icon: 'package', t: 'Tracking a package — <b>out for delivery</b>, ETA 14:20.', meta: 'Live' },
    { icon: 'plane', t: 'Trip to <b>Porto</b> next Friday — flights & hotel saved.', meta: 'Reference' },
  ]},
];

/* ---- HISTORY: timestamped, grouped by recency/context ---- */
const HISTORY = [
  { group: 'Earlier today', count: 5, items: [
    { time: '13:48', q: 'Show me the home network', type: 'Network map', tags: ['Devices', 'On-screen'], acc: true },
    { time: '11:12', q: 'Photos from the Porto scouting trip', type: 'Gallery', tags: ['Images', 'Phone'] },
    { time: '09:31', q: 'What\'s on my calendar today?', type: 'Schedule', tags: ['Calendar', 'Voice'] },
    { time: '08:00', q: 'Morning brief', type: 'Briefing', tags: ['Scheduled', 'Auto'], acc: true },
    { time: '07:42', q: 'Is the deploy window still at 15:00?', type: 'Answer', tags: ['Voice', 'Phone'] },
  ]},
  { group: 'Yesterday', count: 3, items: [
    { time: '21:10', q: 'Dim the studio lights to 30%', type: 'Action', tags: ['Devices', 'Voice'] },
    { time: '16:25', q: 'Summarize the Console v2 review notes', type: 'Answer', tags: ['Docs'] },
    { time: '14:03', q: 'Front door — who was that?', type: 'Network map', tags: ['Camera', 'Event'], acc: true },
  ]},
  { group: 'This week · Porto trip', count: 4, items: [
    { time: 'Mon', q: 'Find hotels near Ribeira under €180', type: 'Answer', tags: ['Research'] },
    { time: 'Mon', q: 'Show me the riverfront at sunset', type: 'Gallery', tags: ['Images'] },
    { time: 'Sun', q: 'Flights Lisbon → Porto Friday morning', type: 'Answer', tags: ['Research', 'Phone'] },
    { time: 'Sun', q: 'Block Friday afternoon for travel', type: 'Schedule', tags: ['Calendar'] },
  ]},
];

/* ---- proactive / self-triggered events ---- */
const EVENTS = [
  { id: 'door', source: 'Front Door Cam', icon: 'video',
    toast: { lead: 'Motion at the front door', sub: 'A delivery courier — package matches your tracked parcel.' },
    respond: 'door-motion' },
  { id: 'deploy', source: 'Deploy watcher', icon: 'git-branch',
    toast: { lead: 'prod-eu deploy starting', sub: 'Health looks nominal. I\'ll watch error rates.' },
    respond: 'deploy' },
  { id: 'brief', source: 'Schedule', icon: 'sunrise',
    toast: { lead: 'Your morning brief is ready', sub: '3 meetings, clear skies, 1 deploy window.' },
    respond: 'calendar' },
];

/* ---- input source presets (for remote-trigger demo) ---- */
const SOURCES = [
  { id: 'screen', label: 'This screen', icon: 'monitor' },
  { id: 'phone', label: 'Phone', icon: 'smartphone' },
  { id: 'office', label: 'Office mic', icon: 'mic' },
];

/* ============================================================
   INTENT ROUTER — maps a query string to a response object
   ============================================================ */
function routeIntent(raw) {
  const q = (raw || '').toLowerCase().trim();
  const has = (...words) => words.some(w => q.includes(w));

  if (has('network', 'devices', 'wifi', 'wi-fi', 'router', 'door', 'camera', 'map', 'connected', 'online'))
    return { type: 'devicemap', query: raw };

  if (has('photo', 'image', 'picture', 'gallery', 'show me', 'porto', 'trip', 'riverfront', 'sunset', 'scout'))
    return { type: 'gallery', query: raw };

  if (has('calendar', 'schedule', 'today', 'tomorrow', 'meeting', 'agenda', 'brief', 'standup', 'free', 'busy'))
    return { type: 'calendar', query: raw };

  return { type: 'text', query: raw };
}

/* suggestion prompts on the idle screen — each maps cleanly to a response type */
const SUGGESTIONS = [
  { icon: 'radio', label: 'Show me the home network', },
  { icon: 'calendar-days', label: 'What\'s on today?' },
  { icon: 'images', label: 'Photos from the Porto trip' },
  { icon: 'sparkles', label: 'How\'s the deploy looking?' },
];

Object.assign(window, {
  GAL_GRADIENTS, DEVICES, CAL_EVENTS, MEMORY, HISTORY, EVENTS, SOURCES, SUGGESTIONS, routeIntent,
});
