
server {
    # The following directives may only be specified in one of the server blocks
    http2 on;
    http3 on;
    http3_hq on;
    quic_retry on;

    # Listen on UDP for QUIC+HTTP/3
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;

    # Listen on standard HTTP/2 and HTTPS ports
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name api.poliro.local;

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # SSL configuration
    ssl_certificate     /etc/nginx/selfsigned/fullchain.pem;
    ssl_certificate_key /etc/nginx/selfsigned/privkey.pem;
    # TLSv1.3 is required for QUIC.
    ssl_protocols TLSv1.2 TLSv1.3;  # Use only modern, secure TLS versions

    # Max client body size
    client_max_body_size 128M;

    # Increase default request timeout from 60 to 300 seconds
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    default_type application/json;

    # Include default error response formats
    include error_responses.conf;

    # Advertise that QUIC is available
    add_header Alt-Svc 'h3=":443"; ma=86400;';
    add_header X-Robots-Tag "noindex, nofollow" always;
    # 0-RTT QUIC connection resumption
    ssl_early_data on;

    location / {
        # Handle CORS preflight requests
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://poliro.local' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, PATCH, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Max-Age' 86400;
            add_header 'X-Robots-Tag' 'noindex, nofollow' always;
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain';
            return 204;
        }

        proxy_pass http://uvicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location = /robots.txt {
        default_type text/plain;
        access_log off;
        log_not_found off;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name api.poliro.local;

    add_header X-Robots-Tag "noindex, nofollow" always;

    location = /robots.txt {
        default_type text/plain;
        access_log off;
        log_not_found off;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    # Socket.IO proxy
    location /socket.io/ {
        allow all;  # Allow all requests to /public

        proxy_pass http://socketio_nodes;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;

        proxy_redirect off;
        proxy_buffering off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        # Permanent redirect which preserves the request method
        return 308 https://$host$request_uri;
    }
}
